**ATTRIBUTES

+ IC: (continuous)
+ OCSO: (continuous)
+ OCOMO: (continuous)
+ TAB: (continuous)
+ SCP: (continuous)
+ FCC: (continuous)
+ GPRS: (continuous)
+ Class: [1, 2, 3]

decision: Class

**PREFERENCES

IC: gain
OCSO: gain
OCOMO: gain
TAB: gain
SCP: gain
FCC: cost
GPRS: gain
Class: gain
q1: gain
q2: gain
q3: gain
Class: gain


**FILEINFO

DATE: "Mon Apr 09 11:01:11 CEST 2012"
AUTHOR: "milosz"
REM: "File created using jMAF"

**EXAMPLES
a1: 2 3 2 3 1 1 1 3
a2: 2 3 2 1 1 3 2 3
a3: 1 1 1 1 1 1 1 1
a4: 1 2 1 3 3 1 2 3
a5: 3 3 2 1 3 1 1 2
a6: 1 1 1 1 2 1 1 1
a7: 2 3 2 2 3 1 2 3
a8: 1 3 2 3 2 1 2 2
a9: 3 3 2 4 3 2 2 1
a10: 1 3 2 1 2 2 2 2
a11: 3 3 2 4 3 1 2 3
a12: 1 1 1 1 1 3 2 1
a13: 3 1 1 1 2 2 1 2
a14: 1 1 1 1 3 4 1 1
**END